export const TOAST_NOTIFICATION_ENABLED = 'TOAST_NOTIFICATION_ENABLED';

export const TOAST_NOTIFICATION_DISABLED = 'TOAST_NOTIFICATION_DISABLED';

export const SHOW_TOAST_NOTIFICATION_OPTIONS = 'SHOW_TOAST_NOTIFICATION_OPTIONS';
